### ISSUE TITLE
Can't distribute dateutils

### ISSUE THREAD

**Issue by colltoaction** [seahboonsiew/pyspark-csv#3]
Hi,

I'm using Spark for a university assignment, and my easiest choice was to set up the environment using https://hub.docker.com/r/jupyter/pyspark-notebook/. I need to parse a CSV file so I'm using this module, but I can't get `dateutil` to work. Import fails because it can't find it, even though I run `!conda install python-dateutil` first.

As a workaround, I removed the import from the file and hardcoded `parseDate=False` so I can still use this plugin. If we were able to avoid this dependency, it would be much easier to include this module.

Cheers!

**Comment by inexxt** [comment]
+1, I have problems with dateutil.parser module too
